sonar.projectKey=AlejandroPrieto82_AgroConecta_Front
sonar.organization=agroconecta
sonar.projectName=AgroConecta Front
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.ts,**/*.config.js,**/vite-env.d.ts